### ISSUE TITLE
Is Public Code database beeing deployed to b9d53b?

### ISSUE THREAD

**Issue by RMCampos** [bcgov/public-code#106]
**Describe the question**
There's a deployment into our `test` namespace (project `b9d53b`) labelled `public-code-72-database`. Someone could take a look on that?

**Comment by mishraomp** [comment]
@DerekRoberts I don't think we are using `b9d53b`?

**Comment by mishraomp** [comment]
I am closing this issue as I dont think it is going to that namespace

**Comment by DerekRoberts** [comment]
@RMCampos No idea what's going on there!  Please delete.
