### ISSUE TITLE
Remove Auto Promotion to PROD and Create workflow dispatch for manual promotion

### ISSUE THREAD

**Issue by mishraomp** [bcgov/public-code#136]
Currently merging to main releases to PROD.
Adding reviewers , create issues for the crawler.
as a stop gap measure, remove auto promotion, add workflow dispatch
this should be removed when we have UTs, and automated e2e tests for both api and ui.

@DerekRoberts  thoughts?

**Comment by DerekRoberts** [comment]
@mishraomp Bang on.  Let's get that stuff removed temporarily.
